# Copyright 2020 OPREA OLIVIA MARIA-MAGDALENA <opreaolivia73@gmail.com>

build:
#	g++ -std=c++17 -Wall -Wextra p1.cpp -o p1
	g++ -std=c++17 -Wall -Wextra p2.cpp -o p2
	g++ -std=c++17 -Wall -Wextra p3.cpp -o p3

#run-p1:
#	./p1

run-p2:
	./p2

run-p3:
	./p3

clean:
#	rm -f p1 p2 p3 *.o
	rm -f p2 p3 *.o
