# Copyright 2020 OPREA OLIVIA MARIA-MAGDALENA <opreaolivia73@gmail.com>

build:
	g++ -Wall -Wextra bani.cpp -o bani
	g++ -Wall -Wextra gard.cpp -o gard
	g++ -Wall -Wextra bomboane.cpp -o bomboane
#	g++ -Wall -Wextra sala.cpp -o sala

run-p1:
	./bani

run-p2:
	./gard

run-p3:
	./bomboane

#run-p4:
#	./sala

clean:
#	rm bomboane gard bani sala *.o
	rm bani gard bomboane *.o
